/**
 * Activity Event types — the vocabulary of the bob-ai event system.
 *
 * Every agent action flows through the Activity Hub as a structured event.
 * These types define the shape of those events.
 */

// ---------------------------------------------------------------------------
// Visibility levels
// ---------------------------------------------------------------------------

export type EventVisibility = 'timeline' | 'activity' | 'internal' | 'debug'

// ---------------------------------------------------------------------------
// Base event schema
// ---------------------------------------------------------------------------

export interface ActivityEvent {
  /** UUID, generated by the hub on receipt */
  id: string
  /** Unix milliseconds */
  timestamp: number
  /** Which team this belongs to */
  teamId: string
  /** Which agent emitted it (e.g., "ui", "backend", "lead") */
  agentId: string
  /** Dot-separated namespace (e.g., "tool.invoke", "milestone.achieved") */
  type: string
  /** Event-specific data */
  payload: Record<string, unknown>
  /** Assigned by hub based on visibility rules */
  visibility: EventVisibility
}

// ---------------------------------------------------------------------------
// Core event type constants (dot-separated namespaces)
// ---------------------------------------------------------------------------

export const EventTypes = {
  // Agent lifecycle
  AGENT_SPAWNED: 'agent.spawned',
  AGENT_DEBRIEFED: 'agent.debriefed',
  AGENT_THINKING: 'agent.thinking',
  AGENT_COMPLETED: 'agent.completed',
  AGENT_ERROR: 'agent.error',
  AGENT_PAUSED: 'agent.paused',
  AGENT_RESUMED: 'agent.resumed',

  // Communication
  DELEGATION_SENT: 'delegation.sent',
  MESSAGE_SENT: 'message.sent',

  // Tool use
  TOOL_INVOKE: 'tool.invoke',
  TOOL_RESULT: 'tool.result',
  TOOL_ERROR: 'tool.error',
  TOOL_BATCH: 'tool.batch',

  // Code work
  CODE_CHANGED: 'code.changed',
  CODE_REVIEWED: 'code.reviewed',
  TEST_RUN: 'test.run',
  TEST_PASSED: 'test.passed',
  TEST_FAILED: 'test.failed',

  // Research
  WEB_SEARCH: 'web.search',
  WEB_SCRAPE: 'web.scrape',
  KNOWLEDGE_READ: 'knowledge.read',

  // Progress
  MILESTONE_ACHIEVED: 'milestone.achieved',
  GOAL_COMPLETED: 'goal.completed',
  GOAL_PROGRESS: 'goal.progress',
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]

// ---------------------------------------------------------------------------
// Typed payloads for core event types
// ---------------------------------------------------------------------------

export interface AgentSpawnedPayload {
  role: string
  task: string
  calibration: Record<string, unknown>
}

export interface AgentDebriefedPayload {
  context: string
  plan: string
  subgoals: string[]
}

export interface AgentThinkingPayload {
  step: number
  reasoning: string
}

export interface AgentCompletedPayload {
  result: string
  artifacts: string[]
}

export interface AgentErrorPayload {
  error: string
  recoverable: boolean
}

export interface AgentPausedPayload {
  reason: string
}

export interface DelegationSentPayload {
  from: string
  to: string
  task: string
  context?: string
}

export interface MessageSentPayload {
  from: string
  to: string
  content: string
}

export interface ToolInvokePayload {
  tool: string
  args: unknown
  context?: string
}

export interface ToolResultPayload {
  tool: string
  output: unknown
  duration: number
}

export interface ToolErrorPayload {
  tool: string
  error: string
}

export interface ToolBatchPayload {
  tool: string
  count: number
  items: string[]
}

export interface CodeChangedPayload {
  files: Array<{
    path: string
    additions: number
    deletions: number
    status: 'new' | 'modified' | 'deleted'
  }>
}

export interface CodeReviewedPayload {
  files: string[]
  issues: string[]
  approved: boolean
}

export interface TestRunPayload {
  command: string
  passed: number
  failed: number
  total: number
}

export interface TestResultPayload {
  name: string
  duration?: number
  error?: string
}

export interface WebSearchPayload {
  query: string
  results: Array<{ title: string; url: string; snippet: string }>
}

export interface WebScrapePayload {
  url: string
  summary: string
  wordCount: number
}

export interface KnowledgeReadPayload {
  document: string
  relevant: string
}

export interface MilestoneAchievedPayload {
  title: string
  description?: string
  stats: Record<string, number>
}

export interface GoalCompletedPayload {
  goalId: string
  result: string
}

export interface GoalProgressPayload {
  goalId: string
  progress: number
  current: string
}
